import { Contact, StageDefinition, MessageTemplate, TeamMember, FollowUpItem, WhatsAppMessage } from '../types/crm';

export const INDUSTRY_LABELS = {
  all: 'All Industries',
  real_estate: 'Real Estate',
  car_dealership: 'Car Dealership',
  repair_shop: 'Repair Shop',
  boutique: 'Boutique',
};

export const INDUSTRY_COLORS = {
  all: '#075E54',
  real_estate: '#0284C7',
  car_dealership: '#EA580C',
  repair_shop: '#D97706',
  boutique: '#DB2777',
};

export const STAGE_DEFINITIONS: StageDefinition[] = [
  // Real Estate Stages
  { id: 're_new_inquiry', label: 'New Inquiry', industry: 'real_estate', color: '#38BDF8', order: 1 },
  { id: 're_viewing_scheduled', label: 'Viewing Booked', industry: 'real_estate', color: '#0284C7', order: 2 },
  { id: 're_offer_submitted', label: 'Offer Submitted', industry: 'real_estate', color: '#F59E0B', order: 3 },
  { id: 're_under_contract', label: 'Under Contract', industry: 'real_estate', color: '#8B5CF6', order: 4 },
  { id: 're_closed_won', label: 'Deal Closed', industry: 'real_estate', color: '#10B981', order: 5 },

  // Car Dealership Stages
  { id: 'car_lead_in', label: 'Inbound Lead', industry: 'car_dealership', color: '#FDBA74', order: 1 },
  { id: 'car_test_drive', label: 'Test Drive Booked', industry: 'car_dealership', color: '#EA580C', order: 2 },
  { id: 'car_trade_eval', label: 'Trade-in / Finance', industry: 'car_dealership', color: '#F59E0B', order: 3 },
  { id: 'car_offer_sent', label: 'Proposal Sent', industry: 'car_dealership', color: '#8B5CF6', order: 4 },
  { id: 'car_delivered', label: 'Vehicle Delivered', industry: 'car_dealership', color: '#10B981', order: 5 },

  // Repair Shop Stages
  { id: 'rep_diagnostic', label: 'Diagnostic Needed', industry: 'repair_shop', color: '#FCD34D', order: 1 },
  { id: 'rep_quote_sent', label: 'Quote Pending Approval', industry: 'repair_shop', color: '#D97706', order: 2 },
  { id: 'rep_in_progress', label: 'Repair In Progress', industry: 'repair_shop', color: '#3B82F6', order: 3 },
  { id: 'rep_ready', label: 'Ready for Pickup', industry: 'repair_shop', color: '#10B981', order: 4 },
  { id: 'rep_completed', label: 'Paid & Collected', industry: 'repair_shop', color: '#059669', order: 5 },

  // Boutique Stages
  { id: 'bt_catalog', label: 'Catalog Browsing', industry: 'boutique', color: '#F472B6', order: 1 },
  { id: 'bt_fitting', label: 'Fitting / Hold', industry: 'boutique', color: '#DB2777', order: 2 },
  { id: 'bt_invoice', label: 'Invoice Generated', industry: 'boutique', color: '#F59E0B', order: 3 },
  { id: 'bt_order_placed', label: 'Order Processing', industry: 'boutique', color: '#8B5CF6', order: 4 },
  { id: 'bt_delivered', label: 'Fulfilled / VIP Loyalty', industry: 'boutique', color: '#10B981', order: 5 },
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'team_1',
    name: 'Sarah Jenkins',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    email: 'sarah.j@primecrm.io',
    phone: '+1 (555) 019-2831',
    active: true,
  },
  {
    id: 'team_2',
    name: 'Marcus Vance',
    role: 'Sales Agent',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'marcus.v@primecrm.io',
    phone: '+1 (555) 019-4822',
    active: true,
  },
  {
    id: 'team_3',
    name: 'Elena Rostova',
    role: 'Service Advisor',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    email: 'elena.r@primecrm.io',
    phone: '+1 (555) 019-7711',
    active: true,
  },
  {
    id: 'team_4',
    name: 'Chloe Monet',
    role: 'Stylist',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'chloe.m@primecrm.io',
    phone: '+1 (555) 019-3390',
    active: true,
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'contact_1',
    name: 'Marcus Thorne',
    phone: '+1 (555) 234-8901',
    email: 'm.thorne@vanguard.io',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    industry: 'real_estate',
    stageId: 're_viewing_scheduled',
    dealValue: 850000,
    dealTitle: 'Skyline Penthouse (3 Bed / 3.5 Bath)',
    assignedTo: 'team_2',
    unreadCount: 2,
    lastMessageText: 'Can you confirm if the private rooftop terrace is included in the HOA fee?',
    lastMessageTime: '10:42 AM',
    tags: ['Penthouse', 'High Intent', 'Cash Buyer', 'WhatsApp QR'],
    followUpDate: '2026-09-20',
    followUpNote: 'Host in-person tour on 34th floor and provide building bylaws.',
    notes: [
      {
        id: 'note_1',
        authorId: 'team_2',
        authorName: 'Marcus Vance',
        text: 'Pre-qualified with Chase Private Client. Wants to close before end of Q4.',
        timestamp: 'Yesterday at 4:15 PM',
      },
    ],
    customFields: {
      'Property Type': 'Condo Penthouse',
      'Target Budget': '$850,000 - $920,000',
      'Preferred Move-In': 'November 2026',
      'Square Footage': '2,400 sq ft',
    },
    createdAt: '2026-09-12',
    source: 'WhatsApp QR',
  },
  {
    id: 'contact_2',
    name: 'Alex Rivera',
    phone: '+1 (555) 782-4412',
    email: 'alex.rivera@motorsport.co',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    industry: 'car_dealership',
    stageId: 'car_test_drive',
    dealValue: 118500,
    dealTitle: '2025 Audi RS6 Avant Quattro',
    assignedTo: 'team_1',
    unreadCount: 1,
    lastMessageText: 'Sounds great! I will be at the dealership tomorrow at 3 PM with my driver license.',
    lastMessageTime: '09:15 AM',
    tags: ['Test Drive', 'Performance Wagon', 'Financing', 'Instagram Ad'],
    followUpDate: '2026-09-20',
    followUpNote: 'Prepare dealer plate and fuel up RS6 Avant for 3:00 PM appointment.',
    notes: [
      {
        id: 'note_2',
        authorId: 'team_1',
        authorName: 'Sarah Jenkins',
        text: 'Trading in 2021 BMW M5 Competition. Title in hand.',
        timestamp: 'Sep 17, 2026',
      },
    ],
    customFields: {
      'Vehicle VIN': 'WAUR4GB82PN091244',
      'Exterior Color': 'Nardo Gray',
      'Trade-in Vehicle': '2021 BMW M5 (34k miles)',
      'Estimated Trade': '$62,000',
    },
    createdAt: '2026-09-15',
    source: 'Instagram Ad',
  },
  {
    id: 'contact_3',
    name: 'Hannah Baker',
    phone: '+1 (555) 901-3482',
    email: 'hannah.b@designstudio.org',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    industry: 'repair_shop',
    stageId: 'rep_ready',
    dealValue: 640,
    dealTitle: 'Mercedes C300 Brake Pad & Rotor Service',
    assignedTo: 'team_3',
    unreadCount: 0,
    lastMessageText: 'Your Mercedes C300 inspection & brake service is completed and ready for pickup!',
    lastMessageTime: 'Yesterday',
    tags: ['Ready Pickup', 'Warranty 24mo', 'Repeat Customer', 'Walk-in'],
    followUpDate: '2026-09-21',
    followUpNote: 'Send post-service satisfaction survey & invoice link.',
    notes: [
      {
        id: 'note_3',
        authorId: 'team_3',
        authorName: 'Elena Rostova',
        text: 'Ceramic brake pads installed front and rear. Fluid flushed. Test driven 4 miles.',
        timestamp: 'Yesterday at 3:30 PM',
      },
    ],
    customFields: {
      'Vehicle': '2020 Mercedes C300 4MATIC',
      'License Plate': '7KLR912',
      'Mileage': '58,240 mi',
      'Tech Assigned': 'Bay 3 - Alex T.',
    },
    createdAt: '2026-09-17',
    source: 'Walk-in',
  },
  {
    id: 'contact_4',
    name: 'Isabella Rossi',
    phone: '+1 (555) 431-8921',
    email: 'isabella.rossi@couture.it',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    industry: 'boutique',
    stageId: 'bt_fitting',
    dealValue: 3200,
    dealTitle: 'Emerald Silk Evening Gown & Diamond Clutch',
    assignedTo: 'team_4',
    unreadCount: 3,
    lastMessageText: 'Could you reserve the matching velvet cape for my private fitting session?',
    lastMessageTime: '11:05 AM',
    tags: ['VIP Client', 'Private Fitting', 'Autumn Gala', 'Website Widget'],
    followUpDate: '2026-09-19',
    followUpNote: 'Prepare Champagne & suite 2 with size 38 and 40 silk gowns.',
    notes: [
      {
        id: 'note_4',
        authorId: 'team_4',
        authorName: 'Chloe Monet',
        text: 'Attending Met Gala charity event next month. Highly discerning shopper.',
        timestamp: 'Today at 9:00 AM',
      },
    ],
    customFields: {
      'Dress Size': 'EU 38 / US 4',
      'Fabric Preference': 'Pure Mulberry Silk',
      'Event Date': 'Oct 14, 2026',
      'VIP Tier': 'Platinum Star ($12k LTV)',
    },
    createdAt: '2026-09-10',
    source: 'Website Widget',
  },
  {
    id: 'contact_5',
    name: 'Sophia Chen',
    phone: '+1 (555) 672-1190',
    email: 'sophia.chen@techglobal.net',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    industry: 'real_estate',
    stageId: 're_offer_submitted',
    dealValue: 620000,
    dealTitle: 'Oakridge Modern Family Villa (4 Bed / 3 Bath)',
    assignedTo: 'team_2',
    unreadCount: 0,
    lastMessageText: 'The sellers counter-offered at $615,000 with inspection contingency included.',
    lastMessageTime: 'Sep 18',
    tags: ['Negotiation', 'Contingent', 'Real Estate', 'Referral'],
    followUpDate: '2026-09-20',
    followUpNote: 'Follow up on buyer acceptance of $615k counter-offer.',
    notes: [
      {
        id: 'note_5',
        authorId: 'team_2',
        authorName: 'Marcus Vance',
        text: 'Pre-approved with Wells Fargo 30-yr fixed. Earnest money deposit ready.',
        timestamp: 'Sep 18 at 2:00 PM',
      },
    ],
    customFields: {
      'Property Address': '442 Oakridge Meadow Way',
      'Initial Offer': '$600,000',
      'Counter Offer': '$615,000',
      'Contingencies': 'Inspection + Financing',
    },
    createdAt: '2026-09-08',
    source: 'Referral',
  },
  {
    id: 'contact_6',
    name: 'Carlos Mendez',
    phone: '+1 (555) 349-8801',
    email: 'cmendez@speedlabs.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    industry: 'repair_shop',
    stageId: 'rep_quote_sent',
    dealValue: 1250,
    dealTitle: 'BMW E92 M3 Throttle Actuator Replacement',
    assignedTo: 'team_3',
    unreadCount: 1,
    lastMessageText: 'Hi Carlos, the diagnostic showed bank 1 actuator failure. Quote is attached for your approval.',
    lastMessageTime: 'Sep 18',
    tags: ['Quote Sent', 'Diagnostics', 'WhatsApp QR'],
    followUpDate: '2026-09-21',
    followUpNote: 'Check if Carlos approves the OEM actuator quote before ordering parts.',
    notes: [],
    customFields: {
      'Vehicle': '2011 BMW M3 Coupe',
      'Fault Code': '2B15 & 2B21 Throttle Actuator',
      'Estimated Labor': '3.5 Hours',
    },
    createdAt: '2026-09-16',
    source: 'WhatsApp QR',
  },
  {
    id: 'contact_7',
    name: 'Liam O’Connor',
    phone: '+1 (555) 812-7729',
    email: 'liam.oc@artisanleather.com',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    industry: 'boutique',
    stageId: 'bt_order_placed',
    dealValue: 1850,
    dealTitle: 'Handcrafted Tuscan Leather Weekender & Jacket',
    assignedTo: 'team_4',
    unreadCount: 0,
    lastMessageText: 'Your custom leather duffle is in final stitching at the Florence atelier.',
    lastMessageTime: 'Sep 17',
    tags: ['Bespoke Order', 'Overseas Craft', 'Paid in Full'],
    followUpDate: '2026-09-24',
    followUpNote: 'Tracking number will be generated when shipment arrives at DHL hub.',
    notes: [],
    customFields: {
      'Monogram Initial': 'L.O.C in Gold Foil',
      'Leather Shade': 'Cognac Antique',
      'Expected Delivery': 'Sept 28, 2026',
    },
    createdAt: '2026-09-05',
    source: 'Website Widget',
  },
  {
    id: 'contact_8',
    name: 'Emily Watson',
    phone: '+1 (555) 492-3320',
    email: 'e.watson@greentech.org',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    industry: 'car_dealership',
    stageId: 'car_trade_eval',
    dealValue: 56900,
    dealTitle: '2024 Porsche Macan T',
    assignedTo: 'team_1',
    unreadCount: 0,
    lastMessageText: 'We completed the Black Book appraisal on your Tesla Model 3 at $26,500.',
    lastMessageTime: 'Sep 17',
    tags: ['EV Trade', 'Porsche Buyer', 'Credit Approved'],
    followUpDate: '2026-09-22',
    followUpNote: 'Send updated financing spreadsheet with trade equity subtracted.',
    notes: [],
    customFields: {
      'Desired Car': 'Porsche Macan T (Carrara White)',
      'Current Car': '2022 Tesla Model 3 Performance',
      'Finance Term': '48 Months at 4.9%',
    },
    createdAt: '2026-09-14',
    source: 'Referral',
  },
];

export const INITIAL_MESSAGES: Record<string, WhatsAppMessage[]> = {
  contact_1: [
    {
      id: 'm1_1',
      sender: 'customer',
      text: 'Hello, I saw your WhatsApp QR code on the listing board at the Grand Harbor Tower. Is penthouse #34B still on the market?',
      timestamp: '2026-09-18T09:12:00Z',
    },
    {
      id: 'm1_2',
      sender: 'business',
      text: 'Good morning Marcus! Yes, Penthouse 34B is currently available. It features 2,400 sq ft, 3 en-suite bedrooms, private elevator vestibule, and panoramic city/bay views.',
      timestamp: '2026-09-18T09:14:00Z',
      status: 'read',
    },
    {
      id: 'm1_3',
      sender: 'business',
      text: 'Here is the full property brochure with high-resolution floor plans and recent HOA inclusions for your review.',
      timestamp: '2026-09-18T09:15:00Z',
      status: 'read',
      hasAttachment: true,
      attachmentType: 'document',
      attachmentTitle: 'Grand_Harbor_PH34B_Brochure.pdf (4.8 MB)',
    },
    {
      id: 'm1_4',
      sender: 'customer',
      text: 'That looks stunning. We are ready to view it this weekend. What times are available on Saturday?',
      timestamp: '2026-09-18T09:40:00Z',
    },
    {
      id: 'm1_5',
      sender: 'business',
      text: 'I have exclusive private slots open at 11:00 AM or 2:00 PM this Saturday. Which one fits your schedule better?',
      timestamp: '2026-09-18T09:43:00Z',
      status: 'read',
    },
    {
      id: 'm1_6',
      sender: 'customer',
      text: 'Let us lock in Saturday at 2:00 PM please. Will concierge parking be available?',
      timestamp: '2026-09-19T08:15:00Z',
    },
    {
      id: 'm1_7',
      sender: 'business',
      text: 'Confirmed for Saturday at 2:00 PM! Valet parking is reserved under your name "Marcus Thorne". I have sent calendar invitation to your email.',
      timestamp: '2026-09-19T08:20:00Z',
      status: 'read',
    },
    {
      id: 'm1_8',
      sender: 'customer',
      text: 'Can you confirm if the private rooftop terrace is included in the HOA fee?',
      timestamp: '2026-09-19T10:42:00Z',
    },
  ],
  contact_2: [
    {
      id: 'm2_1',
      sender: 'customer',
      text: 'Hi, I tapped your Instagram ad regarding the 2025 Audi RS6 Avant in Nardo Gray. Is it still in stock?',
      timestamp: '2026-09-18T14:10:00Z',
    },
    {
      id: 'm2_2',
      sender: 'business',
      text: 'Hi Alex! Yes, the 2025 RS6 Avant Quattro in Nardo Gray with Carbon Optic Package and Dynamic Plus Package just rolled onto our showroom floor today.',
      timestamp: '2026-09-18T14:12:00Z',
      status: 'read',
    },
    {
      id: 'm2_3',
      sender: 'business',
      text: 'Here is the Monroney window sticker with full options breakdown ($118,500 MSRP).',
      timestamp: '2026-09-18T14:13:00Z',
      status: 'read',
      hasAttachment: true,
      attachmentType: 'document',
      attachmentTitle: '2025_Audi_RS6_WindowSticker.pdf',
    },
    {
      id: 'm2_4',
      sender: 'customer',
      text: 'Awesome spec. Can we schedule a test drive tomorrow afternoon? I also have a 2021 BMW M5 I want to trade in.',
      timestamp: '2026-09-19T08:50:00Z',
    },
    {
      id: 'm2_5',
      sender: 'business',
      text: 'Absolutely! Our appraisal manager can inspect your M5 while you are out on the test drive with the RS6.',
      timestamp: '2026-09-19T09:02:00Z',
      status: 'read',
    },
    {
      id: 'm2_6',
      sender: 'customer',
      text: 'Sounds great! I will be at the dealership tomorrow at 3 PM with my driver license.',
      timestamp: '2026-09-19T09:15:00Z',
    },
  ],
  contact_3: [
    {
      id: 'm3_1',
      sender: 'customer',
      text: 'Hi Elena, dropped off my 2020 C300 this morning for the front brake squeal.',
      timestamp: '2026-09-17T08:30:00Z',
    },
    {
      id: 'm3_2',
      sender: 'business',
      text: 'Good morning Hannah! Our technician Alex put it on the lift. The front pads are down to 2mm and rotors show moderate grooving. Here is the digital inspection report.',
      timestamp: '2026-09-17T11:15:00Z',
      status: 'read',
      hasAttachment: true,
      attachmentType: 'document',
      attachmentTitle: 'Mercedes_C300_Inspection_Report.pdf',
    },
    {
      id: 'm3_3',
      sender: 'customer',
      text: 'Approved! Please go ahead with the Brembo ceramic package as quoted.',
      timestamp: '2026-09-17T11:45:00Z',
    },
    {
      id: 'm3_4',
      sender: 'business',
      text: 'Your Mercedes C300 inspection & brake service is completed and ready for pickup!',
      timestamp: '2026-09-18T15:20:00Z',
      status: 'read',
    },
  ],
  contact_4: [
    {
      id: 'm4_1',
      sender: 'customer',
      text: 'Hello Chloe! I loved the Autumn Gala lookbook you sent earlier this week.',
      timestamp: '2026-09-19T08:20:00Z',
    },
    {
      id: 'm4_2',
      sender: 'business',
      text: 'Bonjour Isabella! That emerald silk gown by Maison V was designed with your gala evening in mind. We received the matching clutch from Milan today.',
      timestamp: '2026-09-19T08:45:00Z',
      status: 'read',
    },
    {
      id: 'm4_3',
      sender: 'customer',
      text: 'Could you reserve the matching velvet cape for my private fitting session?',
      timestamp: '2026-09-19T11:05:00Z',
    },
  ],
  contact_5: [
    {
      id: 'm5_1',
      sender: 'customer',
      text: 'Hi Marcus, did the listing agent respond to our initial $600k offer on the Oakridge Villa?',
      timestamp: '2026-09-18T13:00:00Z',
    },
    {
      id: 'm5_2',
      sender: 'business',
      text: 'The sellers counter-offered at $615,000 with inspection contingency included.',
      timestamp: '2026-09-18T14:30:00Z',
      status: 'read',
    },
  ],
  contact_6: [
    {
      id: 'm6_1',
      sender: 'customer',
      text: 'Hey Elena, my E92 M3 threw a half engine limp mode warning on the highway.',
      timestamp: '2026-09-18T09:00:00Z',
    },
    {
      id: 'm6_2',
      sender: 'business',
      text: 'Hi Carlos, the diagnostic showed bank 1 actuator failure. Quote is attached for your approval.',
      timestamp: '2026-09-18T16:00:00Z',
      status: 'read',
    },
  ],
  contact_7: [
    {
      id: 'm7_1',
      sender: 'customer',
      text: 'Checking in on the status of my weekender bag and jacket order.',
      timestamp: '2026-09-17T10:00:00Z',
    },
    {
      id: 'm7_2',
      sender: 'business',
      text: 'Your custom leather duffle is in final stitching at the Florence atelier.',
      timestamp: '2026-09-17T12:00:00Z',
      status: 'read',
    },
  ],
  contact_8: [
    {
      id: 'm8_1',
      sender: 'customer',
      text: 'Hi Sarah, did you get the VIN info on my Model 3 trade-in?',
      timestamp: '2026-09-17T11:30:00Z',
    },
    {
      id: 'm8_2',
      sender: 'business',
      text: 'We completed the Black Book appraisal on your Tesla Model 3 at $26,500.',
      timestamp: '2026-09-17T15:00:00Z',
      status: 'read',
    },
  ],
};

export const INITIAL_TEMPLATES: MessageTemplate[] = [
  // Real Estate Templates
  {
    id: 'tmpl_re_1',
    title: 'Property Viewing Confirmation',
    industry: 'real_estate',
    category: 'Confirmation',
    shortcut: '/viewing',
    content: 'Hi {{name}}, confirming your private property tour for {{dealTitle}} on {{date}}. Valet parking is reserved. If you need directions or have any questions beforehand, please let us know!',
  },
  {
    id: 'tmpl_re_2',
    title: 'Brochure & Floor Plan Drop',
    industry: 'real_estate',
    category: 'Quote',
    shortcut: '/brochure',
    content: 'Hello {{name}}! Attached is the official brochure and layout for {{dealTitle}}. It includes complete HOA breakdowns, tax history, and nearby amenities. Let me know when you’d like to see it in person.',
  },
  {
    id: 'tmpl_re_3',
    title: 'Post-Viewing Follow-Up',
    industry: 'real_estate',
    category: 'Follow-up',
    shortcut: '/postview',
    content: 'Hi {{name}}, thank you for touring {{dealTitle}} today. What were your thoughts on the layout and views? Would you like me to prepare a comparative market analysis (CMA) for this property?',
  },

  // Car Dealership Templates
  {
    id: 'tmpl_car_1',
    title: 'Test Drive VIP Booking',
    industry: 'car_dealership',
    category: 'Confirmation',
    shortcut: '/testdrive',
    content: 'Hello {{name}}, your test drive appointment for the {{dealTitle}} is confirmed for {{date}}. Please bring your valid driver license and insurance card. We will have the vehicle freshly washed and parked out front!',
  },
  {
    id: 'tmpl_car_2',
    title: 'Trade-In Appraisal Estimate',
    industry: 'car_dealership',
    category: 'Quote',
    shortcut: '/tradein',
    content: 'Hi {{name}}, great news! Our appraisal team completed the evaluation on your trade-in vehicle. We can offer you competitive market equity towards your purchase of {{dealTitle}}. Are you free for a quick 5-min call to review the numbers?',
  },
  {
    id: 'tmpl_car_3',
    title: 'Finance Rate Pre-Approval',
    industry: 'car_dealership',
    category: 'Status Update',
    shortcut: '/finance',
    content: 'Hi {{name}}, your financing approval for {{dealTitle}} has been processed at our preferred APR tier. We have flexible terms from 36 to 72 months available. Let me know which monthly payment target works best for you.',
  },

  // Repair Shop Templates
  {
    id: 'tmpl_rep_1',
    title: 'Digital Inspection & Quote Ready',
    industry: 'repair_shop',
    category: 'Quote',
    shortcut: '/quote',
    content: 'Hi {{name}}, our technician finished the multi-point diagnostic on your vehicle for {{dealTitle}}. The full estimate and photo inspection report are ready for your review. Please reply APPROVED to authorize the work.',
  },
  {
    id: 'tmpl_rep_2',
    title: 'Vehicle Ready for Pickup',
    industry: 'repair_shop',
    category: 'Status Update',
    shortcut: '/pickup',
    content: 'Hi {{name}}, your vehicle service for {{dealTitle}} is completed, quality-checked, and ready for pickup! Our shop is open until 6:30 PM today. You can pay securely via WhatsApp or in person at the front desk.',
  },
  {
    id: 'tmpl_rep_3',
    title: '6-Month Maintenance Due Reminder',
    industry: 'repair_shop',
    category: 'Follow-up',
    shortcut: '/service6m',
    content: 'Hello {{name}}, it has been 6 months since your last scheduled service at our workshop. Keeping your fluids and filters fresh preserves your warranty and performance. Would you like us to reserve a convenient slot next week?',
  },

  // Boutique Templates
  {
    id: 'tmpl_bt_1',
    title: 'Private Styling & Fitting Slot',
    industry: 'boutique',
    category: 'Confirmation',
    shortcut: '/fitting',
    content: 'Bonjour {{name}}, your private styling suite is reserved on {{date}} for {{dealTitle}}. We will have complimentary refreshments and custom size selections waiting for you. Looking forward to hosting you!',
  },
  {
    id: 'tmpl_bt_2',
    title: 'VIP Exclusive Lookbook Drop',
    industry: 'boutique',
    category: 'Promo',
    shortcut: '/vipdrop',
    content: 'Hi {{name}}! As one of our cherished VIP patrons, you have early 48-hour access to our new limited edition collection before it launches publicly. Let me know if you would like me to set aside {{dealTitle}} in your size.',
  },
  {
    id: 'tmpl_bt_3',
    title: 'Order Shipped with Tracking',
    industry: 'boutique',
    category: 'Status Update',
    shortcut: '/shipped',
    content: 'Dear {{name}}, your bespoke order for {{dealTitle}} has been beautifully packaged and handed over to express courier. Tap here to track your delivery in real-time. Thank you for shopping with us!',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpItem[] = [
  {
    id: 'fu_1',
    contactId: 'contact_1',
    contactName: 'Marcus Thorne',
    contactPhone: '+1 (555) 234-8901',
    industry: 'real_estate',
    dueDate: '2026-09-19',
    dueTime: '14:00',
    title: 'Confirm Penthouse 34B Viewing',
    description: 'Call or WhatsApp Marcus to confirm valet parking and penthouse key code with building concierge.',
    isAutomatedWhatsApp: true,
    templateId: 'tmpl_re_1',
    completed: false,
    priority: 'high',
  },
  {
    id: 'fu_2',
    contactId: 'contact_4',
    contactName: 'Isabella Rossi',
    contactPhone: '+1 (555) 431-8921',
    industry: 'boutique',
    dueDate: '2026-09-19',
    dueTime: '16:30',
    title: 'Reserve Velvet Cape in Suite 2',
    description: 'Ensure matching silk accessories and Champagne are arranged before arrival.',
    isAutomatedWhatsApp: false,
    completed: false,
    priority: 'high',
  },
  {
    id: 'fu_3',
    contactId: 'contact_2',
    contactName: 'Alex Rivera',
    contactPhone: '+1 (555) 782-4412',
    industry: 'car_dealership',
    dueDate: '2026-09-20',
    dueTime: '11:00',
    title: 'RS6 Avant Test Drive Prep',
    description: 'Fuel up the RS6 Avant and notify trade-in appraisal team for his 2021 BMW M5.',
    isAutomatedWhatsApp: true,
    templateId: 'tmpl_car_1',
    completed: false,
    priority: 'medium',
  },
  {
    id: 'fu_4',
    contactId: 'contact_3',
    contactName: 'Hannah Baker',
    contactPhone: '+1 (555) 901-3482',
    industry: 'repair_shop',
    dueDate: '2026-09-20',
    dueTime: '17:00',
    title: 'C300 Pickup Notification',
    description: 'Send payment link and confirm key collection before workshop closes at 6:30 PM.',
    isAutomatedWhatsApp: true,
    templateId: 'tmpl_rep_2',
    completed: false,
    priority: 'medium',
  },
  {
    id: 'fu_5',
    contactId: 'contact_5',
    contactName: 'Sophia Chen',
    contactPhone: '+1 (555) 672-1190',
    industry: 'real_estate',
    dueDate: '2026-09-21',
    dueTime: '10:00',
    title: 'Review Counter-Offer at $615k',
    description: 'Follow up on buyer reaction to seller counter-offer with inspection contingency.',
    isAutomatedWhatsApp: false,
    completed: false,
    priority: 'high',
  },
  {
    id: 'fu_6',
    contactId: 'contact_6',
    contactName: 'Carlos Mendez',
    contactPhone: '+1 (555) 349-8801',
    industry: 'repair_shop',
    dueDate: '2026-09-21',
    dueTime: '15:00',
    title: 'Check Throttle Actuator Quote Approval',
    description: 'Contact Carlos before supplier cutoff at 4 PM to guarantee next-day parts delivery.',
    isAutomatedWhatsApp: true,
    templateId: 'tmpl_rep_1',
    completed: false,
    priority: 'medium',
  },
];
